-- Optional local/dev seed data.
-- Safe to re-run because it upserts by slug.

INSERT INTO articles (
	slug,
	status,
	category,
	region,
	hype_level,
	ai_generated,
	agent_run_id,
	tags,
	source_url,
	source_name,
	source_date,
	factcheck_verdict,
	factcheck_confidence,
	factcheck_summary,
	title_ms,
	body_ms,
	reality_check_ms,
	takeaway_ms,
	prompt_question_ms,
	title_en,
	body_en,
	reality_check_en,
	takeaway_en,
	prompt_question_en,
	image_url,
	image_alt,
	image_caption,
	published_at
) VALUES
(
	'test-crocodile-sepang-2026',
	'published',
	'weird',
	'malaysia',
	'high',
	true,
	'test-run-001',
	ARRAY['buaya', 'viral', 'sepang'],
	'https://example.com/source/crocodile-sepang',
	'Sinar Harian',
	'2026-09-02',
	'mostly-true',
	82,
	'<p>Cross-checked with local authority and reporter photos.</p>',
	'Buaya Liar Muncul di Air Pancut Plaza Sepang',
	'<p>Pengunjung di Plaza Sepang terkejut apabila seekor buaya ditemui di kawasan air pancut pusat beli-belah.</p><p>Pihak berkuasa kemudian menutup kawasan berkenaan untuk operasi pemindahan.</p>',
	'<p>Insiden ini memang dilaporkan dan disahkan oleh pihak berkuasa tempatan.</p>',
	'<p>Kawasan berhampiran sungai dan longkang besar boleh menjadi laluan haiwan liar selepas hujan lebat.</p>',
	'<p>Pernahkah anda melihat haiwan liar di tempat awam?</p>',
	'Wild Crocodile Appears in Sepang Mall Fountain',
	'<p>Shoppers at Plaza Sepang were stunned when a crocodile was spotted in the mall fountain area.</p><p>Authorities later sealed off the location and relocated the animal.</p>',
	'<p>The incident was reported and confirmed by local authorities.</p>',
	'<p>Areas near rivers and large drainage channels can become unexpected wildlife routes after heavy rain.</p>',
	'<p>Have you ever seen a wild animal in a public place?</p>',
	'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=realistic%20news%20photo%20of%20an%20empty%20modern%20shopping%20mall%20fountain%20area%20secured%20by%20authorities%2C%20caution%20tape%2C%20Southeast%20Asia%2C%20editorial%20style&image_size=landscape_16_9',
	'Authorities secure a mall fountain area in Sepang',
	'Illustrative image for the Sepang crocodile story',
	now()
),
(
	'ai-chip-breakthrough-2026',
	'pending',
	'tech',
	'global',
	'medium',
	true,
	'test-run-002',
	ARRAY['ai', 'chips', 'startup'],
	'https://example.com/source/ai-chip-breakthrough',
	'Tech in Asia',
	'2026-09-03',
	'pending',
	64,
	'<p>Primary reporting found, waiting for secondary confirmation.</p>',
	'Syarikat Serantau Dakwa Cipta Cip AI Lebih Jimat Tenaga',
	'<p>Sebuah startup serantau mendakwa cip baharu mereka mampu mengurangkan penggunaan tenaga untuk inferens AI berskala besar.</p><p>Draf ini masih menunggu semakan manusia sebelum diterbitkan.</p>',
	'<p>Dakwaan prestasi belum disahkan oleh makmal bebas.</p>',
	'<p>Bandingkan tuntutan vendor dengan ukuran dunia sebenar sebelum membuat kesimpulan.</p>',
	'<p>Apakah metrik yang paling penting bagi anda: kelajuan, kos, atau kecekapan tenaga?</p>',
	'Regional Startup Claims More Efficient AI Chip',
	'<p>A regional startup claims its new chip can reduce power usage for large-scale AI inference.</p><p>This draft is intentionally left pending for admin review testing.</p>',
	'<p>The performance claim has not yet been independently verified.</p>',
	'<p>Compare vendor claims against real-world benchmarks before drawing conclusions.</p>',
	'<p>Which metric matters most to you: speed, cost, or energy efficiency?</p>',
	'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=realistic%20editorial%20photo%20of%20engineers%20reviewing%20an%20AI%20chip%20prototype%20in%20a%20clean%20modern%20lab%2C%20Southeast%20Asia%2C%20professional%20technology%20news%20style&image_size=landscape_16_9',
	'Engineers reviewing a prototype AI chip',
	'Illustrative image for the AI chip draft',
	NULL
)
ON CONFLICT (slug) DO UPDATE SET
	status = EXCLUDED.status,
	category = EXCLUDED.category,
	region = EXCLUDED.region,
	hype_level = EXCLUDED.hype_level,
	ai_generated = EXCLUDED.ai_generated,
	agent_run_id = EXCLUDED.agent_run_id,
	tags = EXCLUDED.tags,
	source_url = EXCLUDED.source_url,
	source_name = EXCLUDED.source_name,
	source_date = EXCLUDED.source_date,
	factcheck_verdict = EXCLUDED.factcheck_verdict,
	factcheck_confidence = EXCLUDED.factcheck_confidence,
	factcheck_summary = EXCLUDED.factcheck_summary,
	title_ms = EXCLUDED.title_ms,
	body_ms = EXCLUDED.body_ms,
	reality_check_ms = EXCLUDED.reality_check_ms,
	takeaway_ms = EXCLUDED.takeaway_ms,
	prompt_question_ms = EXCLUDED.prompt_question_ms,
	title_en = EXCLUDED.title_en,
	body_en = EXCLUDED.body_en,
	reality_check_en = EXCLUDED.reality_check_en,
	takeaway_en = EXCLUDED.takeaway_en,
	prompt_question_en = EXCLUDED.prompt_question_en,
	image_url = EXCLUDED.image_url,
	image_alt = EXCLUDED.image_alt,
	image_caption = EXCLUDED.image_caption,
	published_at = EXCLUDED.published_at,
	updated_at = now();
